apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myimage2
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: https://github.com/suhaspete/shoppie-master
    path: kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
