apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-frontend-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-frontend-app
  template:
    metadata:
      labels:
        app: my-frontend-app
    spec:
      containers:
        - name: my-frontend-app
          image: myimage2
          ports:
            - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause:
            duration: 60s
        - setWeight: 25
        - pause:
            duration: 60s
        - setWeight: 50
        - pause:
            duration: 60s
        - setWeight: 100

  # Add additional fields as needed
