# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimage2
  template:
    metadata:
      labels:
        app: myimage2
    spec:
      containers:
        - name: myimage2
          image: myimage2 # Update this line with your Docker image
          ports:
            - containerPort: 80
