# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  selector:
    app: myimage2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
